name: Run Tests

on:
    pull_request:
        branches:
            - Terraform-0.12
 
 
jobs:
    test:
        strategy:
            matrix:
                platform: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.platform }}
        steps:
            # if we don't do this, `gofmt` will want to rewrite all Go files due to bad line endings,
            # because Git will convert all line endings to CRLF when cloning on windows
            - name: Set Git to use Linux-style line endings
              run: |
                  git config --global core.autocrlf false
                  git config --global core.eol lf
            - name: Install Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.15
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Setup environment for collection publish
              run: |
                echo "GITHUB_REF=${GITHUB_REF:10}" >> $GITHUB_ENV
                echo "GITHUB_BRANCH=${GITHUB_REF:11}">> $GITHUB_ENV
            - name: Print env
              run:  echo ${{ env.GITHUB_REF }}
            - name: Format  
              run: if ![ -z "$(find . -type f -name "*.go" -not -path "./vendor/*" | sed "s|^\./||" | xargs gofmt -l)" ]; then exit 1; fi
              if: matrix.platform == 'ubuntu-latest'
            - name: Vet
              run: go vet $(go list ./... | grep -v '/vendor/')
            - name: Test
              run: go test -v $(go list ./... | grep -v '/vendor/')
            - name: Login to Docker Hub
              run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            - name: Build the tagged Docker image
              run: docker build . --file Dockerfile --tag nabhajit-ray/hpe-oneview-sdk-for-terraform:${{ env.GITHUB_REF }}-${{ env.GITHUB_BRANCH }}

            - name: Push the tagged Docker image
              run: docker push nabhajit-ray/hpe-oneview-sdk-for-terraform:${{ env.GITHUB_REF }}-${{ env.GITHUB_BRANCH }}    
