name: Run Tests

on:
    pull_request:
        branches:
            - Terraform-0.12
 
 
jobs:
    test:
        strategy:
            matrix:
                platform: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.platform }}
        steps:
            # if we don't do this, `gofmt` will want to rewrite all Go files due to bad line endings,
            # because Git will convert all line endings to CRLF when cloning on windows1
            - name: Set Git to use Linux-style line endings
              run: |
                  git config --global core.autocrlf false
                  git config --global core.eol lf
            - name: Install Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.15
            - name: Checkout code
              uses: actions/checkout@v2
            - name: List File 
              run: ls -ltr
              if: matrix.platform == 'ubuntu-latest'
            - name: List notfmt file
              run: find . -type f -name "*.go" -not -path "./vendor/*" | sed "s|^\./||" | xargs gofmt -l
              if: matrix.platform == 'ubuntu-latest'
            - name: Format  
              run: if [ ! -z "$(find . -type f -name "*.go" -not -path "./vendor/*" | sed "s|^\./||" | xargs gofmt -l)" ]; then exit 1; fi
              if: matrix.platform == 'ubuntu-latest'
            - name: Vet
              run: go vet $(go list ./... | grep -v '/vendor/')
